### ISSUE TITLE
Year list gets appended to document body where this library is not imported, after we visit a page where yearpicker.js is used

### ISSUE THREAD

**Issue by harivnair** [saravanajd/YearPicker#2]
Loading yearpicker.js in the required page appends $template div to the document body. It works fine in the imported page. Now when routing back to any other page(where yearpicker.js is not declared/imported) without refreshing the page of-course, we could see the appended year list in the end of document body. For fixing(way around) it I had to declare yearpicker.js in the parent page so that the $template gets removed. Please fix it in such a way that appending to the document body doesn't reflect in any other page.

**Comment by harivnair** [comment]
Adding upon the above comment - Loading yearpicker.js in the required page appends $template div to the document body. It works fine in the imported page. Now when routing back to any other page(where yearpicker.js is not declared/imported) without refreshing the page of-course, we could see the appended year list in the end of document body. For fixing(way around) it I had to declare yearpicker.js in the parent page so that the $template gets removed. Please fix it in such a way that appending to the document body doen't reflect in any other page.

**Comment by saravanajd** [comment]
Update the yearpicker.js to append next to the input element. for more details you find the demo [here](https://saravanajd.github.io/YearPicker/)
