### ISSUE TITLE
Initial year doesnt set to null

### ISSUE THREAD

**Issue by PrinoyDcosta** [saravanajd/YearPicker#7]
**Describe the bug**
When we use the option year: null , the initial year sets to the current year by default (2021)

**To Reproduce**
1. Set year: null in options
2. open the page and the default year will be selected to the current year

**Expected behavior**
Initial year should be set to blank/null/empty

**Comment by saravanajd** [comment]
I updated the code, Now if you don't provide year value by default the initial year is set to null/empty
